tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "homebrew/cask-fonts"
tap "mongodb/brew"
tap "yt-dlp/taps"
tap "heroku/brew"
tap "stripe/stripe-cli"
brew "fd"
brew "ffmpeg"
brew "fzf"
brew "git" # fix terminal slowness: https://apple.stackexchange.com/questions/119864/xcodebuild-firing-after-every-terminal-command
brew "gnupg" # GNU Privacy Guard, complete and free implementation of OpenPGP standard RFC4880
brew "lua-language-server"
brew "mkcert"
brew "mongodb-community@8.0"
# brew "p7zip"
brew "ripgrep"
brew "stow"
brew "stripe/stripe-cli/stripe"
brew "tldr"
brew "tmux"
brew "watchman"
brew "webp"
brew "wget"
brew "yt-dlp/taps/yt-dlp"
brew "diff-so-fancy"
cask "font-hack-nerd-font"
# cask "font-fantasque-sans-mono"
# cask "alacritty"
# cask "amethyst"
# cask "firefox"
# cask "google-chrome"
# cask "postman"
# cask "lastpass"
# cask "snagit"
# cask "visual-studio-code"
# cask "vlc"
# mas "iStumbler", id: 546033581
# mas "Slack", id: 803453959
