" References
" https://medium.com/actualize-network/how-to-learn-vim-a-four-week-plan-cd8b376a9b85
" https://dougblack.io/words/a-good-vimrc.html

let mapleader="," " leader is comma

syntax enable " enable syntax processing
colorscheme codedark " ~/.vim/colors/codedark.vim

set tabstop=2 " number of visual spaces per tab
set softtabstop=2 " number of spaces in tab when editing
set expandtab " tabs are spaces

set number " show line numbers

set incsearch " search as characters are entered
set hlsearch " highlight matches

set scrolloff=4 " Always keep a few lines above/below cursor at top/bottom of file

" nerdtree
let NERDTreeIgnore=['\.git$[[dir]]', 'node_modules$[[dir]]', '\.swp$[[file]]']
let NERDTreeShowHidden=1
let NERDTreeShowLineNumbers=1

" turn off search highlight
nnoremap <leader><space> :nohlsearch<CR>

" split navigation
nnoremap <C-H> <C-W><C-H>
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>

" browse nerd tree
nnoremap <leader>b :NERDTreeToggle<CR>

" browse recent files
"   then press q followed by number to open
nnoremap <leader>r :browse oldfiles<CR>

