import = ["/Users/lukehow/.config/alacritty/one-dark.toml"]

[font]
size = 20.0

[font.bold]
family = "Hack Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font Mono"
style = "Italic"

[font.normal]
family = "Hack Nerd Font Mono"
style = "Regular"

[shell]
args = ["--login"]
program = "/bin/zsh"

[window]
decorations = "Buttonless"
dynamic_title = true
startup_mode = "Windowed"
title = "Alacritty"
# option_as_alt should be paired with:
# defaults write -g ApplePressAndHoldEnabled -bool false
#
# This disables the accent popup when holding down keys,
# which allows us to hold down alt key for continuous resizing.
option_as_alt = "Both"

[window.padding]
x = 10
y = 10
