[font]
size = 26.0

[font.bold]
family = "Hack Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font Mono"
style = "Italic"

[font.normal]
family = "Hack Nerd Font Mono"
style = "Regular"

[terminal.shell]
args = ["--login"]
program = "/bin/zsh"

[window]
decorations = "Buttonless"
dynamic_title = true
startup_mode = "Windowed"
title = "Alacritty"
# option_as_alt should be paired with:
# defaults write -g ApplePressAndHoldEnabled -bool false
#
# This disables the accent popup when holding down keys,
# which allows us to hold down alt key for continuous resizing.
option_as_alt = "Both"

[window.padding]
x = 10
y = 10

# Colors (One Dark)
# One Dark theme for Alacritty
# https://github.com/alacritty/alacritty-theme/blob/master/themes/one_dark.toml
# Default colors
[colors.primary]
background = '#282c34'
foreground = '#abb2bf'
# Normal colors
[colors.normal]
black   = '#1e2127'
red     = '#e06c75'
green   = '#98c379'
yellow  = '#d19a66'
blue    = '#61afef'
magenta = '#c678dd'
cyan    = '#56b6c2'
white   = '#abb2bf'
# Bright colors
[colors.bright]
black   = '#5c6370'
red     = '#e06c75'
green   = '#98c379'
yellow  = '#d19a66'
blue    = '#61afef'
magenta = '#c678dd'
cyan    = '#56b6c2'
white   = '#ffffff'

